#!/usr/bin/env zsh
#scrot /tmp/screen_locked.png
#convert /tmp/screen_locked.png -scale 10% -scale 1000% /tmp/screen_locked2.png
#i3lock -i /tmp/screen_locked2.png
cd $HOME/dev/config/scripts/wallpaper
i3lock -i $HOME/dev/config/scripts/wallpaper/$(shuf -ezn 1 * | xargs -0 -n1 echo)
